"""add status field to Business

Revision ID: 527e5a4ae70c
Revises: 059757bb5912
Create Date: 2026-02-04 14:29:31.354438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527e5a4ae70c'
down_revision = '059757bb5912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
